name = "agriquant-api"
main = "src/index.py"
compatibility_date = "2024-12-01"
compatibility_flags = ["python_workers"]

# Set WEATHER_API_KEY and ADMIN_PASSWORD with `npx wrangler secret put`.

[[kv_namespaces]]
binding = "COMMENTS"
id = "c480afa2b7564abc8bf82d485c050a0b"
